name: 'Sync mirrorz-help-ng'
on:
  workflow_dispatch:
  schedule:
    - cron: '33 22 * * *'  # 06:33 AM in Asia/Shanghai (UTC+8)
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Sync submodule
      run: |
        git submodule update --remote helpz/_posts
        echo -n 'See content changes in: ' > /tmp/pr_msg
        echo -n 'https://github.com/tuna/mirrorz-help-ng/compare/' >> /tmp/pr_msg
        git diff --submodule=diff | head -n1 | cut -c24-39 >> /tmp/pr_msg
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'helpz: sync mirrorz-help-ng'
        commit-message: 'helpz: sync mirrorz-help-ng'
        author: 'GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>'
        branch: helpz
        delete-branch: true
        body-path: /tmp/pr_msg
